name: 刷步数

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 25 22 * * *
  watch:
    types: started

jobs:
  run-it:
    runs-on: ubuntu-latest
    name: 刷步数
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: 运行时间
      run: |
        time=$(curl "http://quan.suning.com/getSysTime.do")
        echo -e ${time}

    - name: 刷步数账号1
      run: |
        pip install requests
        sckey='${{ secrets.SCKEY }}'
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP }}'
        
        python3 main.py <<EOF
        ${sckey}
        ${user}
        ${pwd}
        ${step}
        EOF

    - name: 刷步数账号2
      run: |
        pip install requests
        sckey='${{ secrets.SCKEY }}'
        user='${{ secrets.USER2 }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP }}'

        python3 main.py <<EOF
        ${sckey}
        ${user}
        ${pwd}
        ${step}
        EOF
